[package]
name = "Api_test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.0.4", features = ["postgres"] }
dotenv = "0.15"
actix-rt = "2"
diesel_migrations = "2.0"
